return {
  "SmiteshP/nvim-navic",
  event = "VeryLazy",
  dependencies = { -- Automatically install LSPs and related tools to stdpath for Neovim
    "neovim/nvim-lspconfig",
  },
  opts = {
    icons = {
      File = " ",
      Module = " ",
      Namespace = " ",
      Package = " ",
      Class = " ",
      Method = " ",
      Property = " ",
      Field = " ",
      Constructor = " ",
      Enum = " ",
      Interface = " ",
      Function = " ",
      Variable = " ",
      Constant = " ",
      String = " ",
      Number = " ",
      Boolean = " ",
      Array = " ",
      Object = " ",
      Key = " ",
      Null = " ",
      EnumMember = " ",
      Struct = " ",
      Event = " ",
      Operator = " ",
      TypeParameter = " ",
    },
    highlight = true,
    click = true,
    lsp = {
      preference = {
        "lua_ls",
        "ts_ls",
        "pyright",
        "rust_analyzer",
        "csharp_ls",
      },
    },
  },
}
